### ISSUE TITLE
Include fisheries vulnerability and unidentified captures in the Stan model

### ISSUE THREAD

**Issue by edwardabraham** [dragonfly-science/seabird-risk-assessment#12]
The Stan model needs to have a fisheries vulnerability parameter included, and to have the unidentified captures represented (this complexity was not included in the original JAGS model).

**Comment by edwardabraham** [comment]
Let us know if you would like to make these changes @otthi

**Comment by otthii** [comment]
@edwardabraham OK, I can do it tomorrow

**Comment by edwardabraham** [comment]
Yep this has now been done :+1:
