### ISSUE TITLE
Order of capture event inside the model and estimation of "p_observable" and "p_live_cap" 

### ISSUE THREAD

**Issue by otthii** [dragonfly-science/seabird-risk-assessment#24]
In my last commit on ['58cf1e7'](https://github.com/dragonfly-science/seabird-risk-assessment/commit/58cf1e760520c125c5bfbc79a0006ee7ec3899de), I've tried to re-write `model/stan/model.stan` in order to change the order of probability events relating to occurrence of seabird bycatch, observability and mortality, and I've changed process to estimate `p_live_cap` and `p_observable`.

I'd like to explain the reason and raise a discussion about the changes.
 
- Considering the chain of causality about occurrence of seabird bycatch, order of sampling equations have to be changed.
  - Total (and true) number of caught birds (related to `q_...`) should be firstly solved and `p_observable` and `p_live_cap` are following.
- `p_live_cap` is estimated just based on observed captures (`DEAD_CAPTURES_O` and `LIVE_CAPTURES_O`)
  - With using observed data, it gives better and more stable estimation for `p_live_cap`.
- `p_observable` is directly estimated inside the model with using raw data of Brothers et al. 2010.
  - While it gives a very weak effect on posterior when the result applied only to prior, it is effective to estimate the parameter simultaneously inside the model.
- `p_observable` and `p_live_cap` are estimated from binomial distribution.

**Comment by edwardabraham** [comment]
Hi @otthii Good questions! This is getting at the heart of the approach. I am aware that a binomial model would be a more usual method. I meant to draw up a  diagram for you this afternoon but haven't got it down, sorry.  A key is that by multiplying by the Poisson means by the probabilities, without drawing the samples, we can then estimate the unidentified captures (by summing the associated means across all the species that the unidentified capture could be). Including unidentified captures is likely to be important, and this approach can be generalised to allow for more structure in the unidentified captures. 

Essentially, we are able to make a probability tree. At the top of the tree are the total incidents. The mean of these incidents for each species and fishery is proportional to the vulnerability and the overlap. Incidents may then be observable or not-observable.  Observable incidents may be identified or non-identified, and each of these categories may be alive or dead.  By comparing the observed live and dead captures for each species with Poisson draws with the appropriate means, and by comparing observed live and dead unidentified captures  with the corresponding Poisson draws, we are able to identify all the parameters.

I need to write up some better technical documentation to explain this model. Maybe this can be one goal for next week!

**Comment by edwardabraham** [comment]
One key point is that a Binomial draw from a Poisson is also Poisson distributed, i.e., if `X|N ~ Binomial(p, N)` and `N ~ Poisson(q)`, then `X ~ Poisson(pq)`. The Binomial-Poisson mixture distribution is a Poisson! (e.g., see [these PDF notes](url=http://www.maths.qmul.ac.uk/~bb/MS_Lectures_9and10.pdf)).

This means that our two approaches are formally equivalent ☺️

**Comment by edwardabraham** [comment]
http://www.maths.qmul.ac.uk/~bb/MS_Lectures_9and10.pdf

**Comment by otthii** [comment]
Good morning @edwardabraham, 

Yes, that's right!  Expected value of mixed distribution both from Poisson and binomial can be expressed by product of those parameters. When I was making the Stan code, I stuck on this problem and also found this solution in [Stan users ML](https://groups.google.com/forum/#!forum/stan-users)🤗.  

One important thing that we need to taking care about is that we have to properly generate total catch with Poisson generator and then reduce unobserved, unidentified and dead number of birds with each binomial trials step by step in the `generated quantities` block when we make a prediction for catch process. Through this procedure, we can understand "uncertainty" of predicted capture.

**Comment by otthii** [comment]
Sorry, I'd like to correct my last comment about calculation of `generated quantities`. Yes, it is no difference overall shape of distribution of predicted values whether we sampled from Poisson distribution with product of expected value and probabilities or step by step process. However, it is possible to occur inconsistency among generated values in each MCMC iteration when we generate multiple predicted values such as observed catch and dead observed catch with separate Poisson sampling with using product of `mu_...`,  `p_observable` and `p_live_cap` even if we use same seed. For example, it is possible that predicted observed catch is 12 but predicted observed live catch is 20. Therefore, still I prefer to use step-by-step approaches for `generated quantities` block.

**Comment by edwardabraham** [comment]
Ahh, yes. Thank-you very much for pointing this out—we should have
generated ` apf_t` and then used binomial sampling to derive the other
quantities. Please feel welcome to submit a pull request to fix this. Note
that we have kept on changing the project structure, so make sure you pull
from the master branch and then start a new branch for your changes.

**Comment by edwardabraham** [comment]
I have added in two diagrams to the project, in `report/diagram` which illustrate how the model parameters are estimated (the probability tree) and then how the fatalities are calculated from the fitted model:

[Estimating the model parameters](https://github.com/dragonfly-science/seabird-risk-assessment/files/1397080/model-probability-tree.pdf)

[Calculating the total fatalities](https://github.com/dragonfly-science/seabird-risk-assessment/files/1397079/model-incident-tree.pdf)
